### ISSUE TITLE
Wide LCD resolution

### ISSUE THREAD

**Issue by BlafKing** [Whiplash141/Whips-Image-Converter#24]
Seems like the resolution of the Wide LCD Panels isn't setup correctly
The image only showed up as a small portion of the original image.
The image worked fine using a custom resolution of 178x108 instead of the default 356x178 when selecting Wide LCD
Not sure if I missed something, or if this is a real issue.
Seemed like it'd be worth sharing either way! :)

**Comment by Whiplash141** [comment]
The wide LCD panel has an aspect ratio of 2:1, so that resolution you mentioned doesn't make much sense to me. I've booted up a clean world and verified that both large and small grid wide LCD panels are indeed 356x178 monospace pixels.

![20210527235758_1](https://user-images.githubusercontent.com/24361564/119931755-96e36400-bf47-11eb-977c-6934ff953c98.jpg)
