### ISSUE TITLE
Fix small grid corner LCD size

### ISSUE THREAD

**Issue by TundraJon** [Whiplash141/Whips-Image-Converter#7]
Hi Whip,
Awesome piece of software you have here, I was so impressed when I found it!  With the latest release, I noticed that the small grid corner LCD images get converted to 178x178, I believe they should be something like 50x178.  I haven't checked all of the other displays, but could if it would help.

I'm sure you get this all the time, but I'd like to see just a couple of additions, if possible.

1. Split images between multiple displays...  I have a pinball table that I need to display on a 2x3 LCD, since one doesn't seem to exist, I'd like to be able to split between 6 LCD's.

2. Since you already have the Custom Resolution grayed out (if not being used), and it's just sitting there...  After selecting the Surface Type and Name, display the resolution the resulting image will have.  This should help with testing and give people a chance to see if what they chose is correct.  (accidentally chose the wrong display name and maybe seeing the resolution would have helped me)

Completely love the program, and am willing to help playtest, if that would take some of the burden off of you.  I'd like to help.

Have a great day,
TJ

**Comment by Whiplash141** [comment]
Hi TJ,

Thanks for the comment. It appears that corner LCDs are different from every other screen in the game as I pulled the screen sizes directly from the game files. I knew I needed to find them empirically, I just never got around to it :P

Regarding your CRs:

1. I'm hesitant to do this for a few reasons. The first is that in multiplayer, each 178x178 image produces 63kB of data to sync to clients. This can bog down multiplayer connections at large scale. The other is that since each pixel is rendered as a different sprite, this can put a lot of load on the render engine and drop framerates when used excessively. A handful of screens isn't that bad, but if I add that feature in, people may go insane with it. (Some already have done it manually on _massive_ composite screens and it hurts my soul)

2. I'll consider that, I'll have to decide if I want users to be able to interact with the sizes or just keep them read-only until they switch into custom size mode.

**Comment by TundraJon** [comment]
Hi Josh,

Thanks for the quick reply.

1. Isn't the 63kb of data to sync only if the display is being viewed? And, if Keen is giving us all of these programmable LCDs, why shouldn't we us them for static images as opposed to running their scripts, which I'm guessing are using more data to keep synced across multiplayer? Lol

Also, if each pixel on a display renders as a separate Sprite, it probably doesn't matter what is on the screen, be it blank or an image or a script. Seems to me, a static image is no more stressful than a blank screen or script.

And besides, you're not forcing people to have to use multiple displays for an image, you're just providing the service. LOL

2. I would highly recommend leaving the numbers read only until they choose custom, it's just less confusing and easier for everyone I would think.

Thank you for creating such an awesome application, and filling a niche that was definitely needed. I truly appreciate all that you have done to make this fantastic game even better.

Have a great week,
TJ

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Whiplash141** [comment]
1. No, that data is synced as soon as you enter sync distance (3km by default). Also, more sprites = more renderer work. Blank screens will always be more performant than filled screens.

2. Yep, that's the direction I'm planning

**Comment by Whiplash141** [comment]
Implemented primary suggestion. Secondary suggestion moved into own issue.
